#additionalArguments:
# Configure your CertificateResolver here...
# 
# HTTP Challenge
# ---
# Generic Example:
#   - --certificatesresolvers.generic.acme.email=your-email@example.com
#   - --certificatesresolvers.generic.acme.caServer=https://acme-v02.api.letsencrypt.org/directory
#   - --certificatesresolvers.generic.acme.httpChallenge.entryPoint=web
#   - --certificatesresolvers.generic.acme.storage=/ssl-certs/acme-generic.json
#
# Prod / Staging Example:
#   - --certificatesresolvers.staging.acme.email=your-email@example.com
#   - --certificatesresolvers.staging.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
#   - --certificatesresolvers.staging.acme.httpChallenge.entryPoint=web
#   - --certificatesresolvers.staging.acme.storage=/ssl-certs/acme-staging.json
#   - --certificatesresolvers.production.acme.email=your-email@example.com
#   - --certificatesresolvers.production.acme.caServer=https://acme-v02.api.letsencrypt.org/directory
#   - --certificatesresolvers.production.acme.httpChallenge.entryPoint=web
#   - --certificatesresolvers.production.acme.storage=/ssl-certs/acme-production.json
#
# DNS Challenge
# ---
# Cloudflare Example:
#  - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
#  - --certificatesresolvers.cloudflare.acme.email=your-email@example.com
#  - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
#  - --certificatesresolvers.cloudflare.acme.storage=/ssl-certs/acme-cloudflare.json
#
# Generic (replace with your DNS provider):
#  - --certificatesresolvers.generic.acme.dnschallenge.provider=generic
#  - --certificatesresolvers.generic.acme.email=your-email@example.com
#  - --certificatesresolvers.generic.acme.storage=/ssl-certs/acme-generic.json

logs:
# Configure log settings here...
  general:
    level: ERROR

ports:
# Configure your entrypoints here...
  traefik:
    port: 8080
    expose:
      default: true
    exposedPort: 8080
  web:
    port: 80
    # (optional) Permanent Redirect to HTTPS
#    redirectTo:
#      port: websecure
  websecure:
    port: 443
    tls:
      enabled: true
      # (optional) Set a Default CertResolver
      # certResolver: cloudflare
  
spec:
  loadBalancerIP: 10.0.20.2

env:
# Set your environment variables here...
# 
# DNS Challenge Credentials
# ---
# Cloudflare Example:
#   - name: CF_API_EMAIL
#     valueFrom:
#       secretKeyRef:
#         key: email
#         name: cloudflare-credentials
#   - name: CF_API_KEY
#     valueFrom:
#       secretKeyRef:
#         key: apiKey
#         name: cloudflare-credentials

persistence:
  enabled: true
  name: nfs-traefik
  path: /etc/traefik/
  existingClaim: nfs-traefik

#deployment:
#  initContainers:
#    # The "volume-permissions" init container is required if you run into permission issues.
#    # Related issue: https://github.com/containous/traefik/issues/6972
#    - name: volume-permissions
#      image: busybox:1.36.1
#      command: ["sh", "-c", "chmod -Rv 600 /etc/traefik/*"]
#      volumeMounts:
#        - name: nfs-traefik
#          mountPath: /etc/traefik/

# Set Traefik as your default Ingress Controller, according to Kubernetes 1.19+ changes.
ingressClass:
  enabled: true
  isDefaultClass: true

# default ingress for Dashboard
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.ian.lan`) && PathPrefix(`/`)
    entryPoints: ["websecure"]

additionalArguments:
- "--api.insecure=true"
# Create the service, middleware and Ingress used to expose the dashboard (can also be created in another way).
# /!\ Yes, you need to replace "changeme" password with a better one. /!\

# Prod / Staging Example:
- --certificatesresolvers.staging.acme.email=ian.blockmans@gmail.com
- --certificatesresolvers.staging.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
- --certificatesresolvers.staging.acme.httpChallenge.entryPoint=web
- --certificatesresolvers.staging.acme.storage=/etc/traefik/certs/acme.json
- --certificatesresolvers.production.acme.email=ian.blockmans@gmail.com
- --certificatesresolvers.production.acme.caServer=https://acme-v02.api.letsencrypt.org/directory
- --certificatesresolvers.production.acme.httpChallenge.entryPoint=web
- --certificatesresolvers.production.acme.storage=/etc/traefik/certs/acme.json

- --providers.file.directory=/etc/traefik/
- --providers.file.watch=true

- --providers.kubernetesingress.ingressendpoint.ip=127.0.0.1

- --providers.redis.endpoints=192.168.1.8:6379

# Ingress Dashboard
#extraObjects:
#  - apiVersion: v1
#    kind: Service
#    metadata:
#      name: traefik-api
#    spec:
#      type: ClusterIP
#      selector:
#        app.kubernetes.io/name: traefik
#        app.kubernetes.io/instance: traefik-default
#      ports:
#      - port: 8080
#        name: traefik
#        targetPort: 8080
#        protocol: TCP
#
#  - apiVersion: networking.k8s.io/v1
#    kind: Ingress
#    metadata:
#      name: traefik-dashboard
#      annotations:
#        traefik.ingress.kubernetes.io/router.entrypoints: websecure
#    spec:
#      rules:
#      - host: traefik.ian.lan
#        http:
#          paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: traefik-api
#                port:
#                  number: 8080
#                  #name: traefik
