apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    targetRevision: 30.0.2
    helm:
      valueFiles:
        - $values/kubernetes/helm/traefik/traefik-values.yaml
      releaseName: traefik
    chart: traefik
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  sources:
    - repoURL: https://traefik.github.io/charts
      targetRevision: 31.0.0
      helm:
        valueFiles:
          - $values/kubernetes/helm/traefik/traefik-values.yaml
        releaseName: traefik
      chart: traefik
    - repoURL: https://github.com/Ian-Blockmans/homelab/
      ref: values

