apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  project: default
  sources:
    - repoURL: https://traefik.github.io/charts
      targetRevision: 30.0.2
      helm:
        releaseName: traefik
        valueFiles:
        - $values/kubernetes/helm/traefik/traefik-values.yaml
      chart: traefik
    - repoURL: https://github.com/Ian-Blockmans/homelab/
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik

