---
- hosts: all

  become: true
  tasks: 
    - name: Backup ssd configs 
      ansible.posix.synchronize:
        src: /disk2/configs/
        dest: /nfs/configs/
        archive: true
        delegate_to: "{{ inventory_hostname }}"
        rsync_opts:
          - "-u"