---
- hosts: all

  tasks:
    - name: restart jellyfin
      docker_container:
        name: media-server-jellyfin-1
        state: started
        restart: yes
        image: jellyfin/jellyfin:latest


    - name: restart plex
      docker_container:
        name: media-server-plex-1
        state: started
        restart: yes