---
- hosts: all

  tasks:
    - name: robocopy appdata
      community.windows.win_robocopy:
        src: C:\Users\ian\AppData\Local\FactoryGame\Saved\SaveGames
        dest: \\192.168.1.5\smbhome\factorygame_backup
        recurse: true
        purge: true