apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-traefik
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    server: 192.168.1.5
    path: "/mnt/spark/NFSdocker/nfsdckr/configs/traefik-kube"
  claimRef:
    name: nfs-traefik
    namespace: traefik