apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-traefik
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumename: nfs-traefik
  resources:
    requests:
      storage: 100Mi