apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  project: default
  source:
    repoURL: https://github.com/Ian-Blockmans/homelab
    path: 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: networking
source:
  helm:
    valueFiles:
    - traefik-values.yaml