apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 30.0.2
    helm:
      releaseName: traefik
  destination:
    server: "https://kubernetes.default.svc"
    namespace: networking
source:
  helm:
    valueFiles:
    - traefik-values.yaml